services:
  - type: web
    name: instagram-text-generator
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --workers 2 --timeout 120
    plan: standard
    # Aumentamos los recursos para manejar el modelo de embeddings
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: OPENAI_API_KEY
        sync: false
    # Añadimos disco persistente para la caché de embeddings
    disk:
      name: embeddings-cache
      mountPath: /opt/render/project/src/cache
      sizeGB: 1
